project:
  type: website
  output-dir: "/Users/max/Desktop/GitHub/maxlorsignol.github.io"
  
resources:
  - "Geomatics_Resume.pdf"

website:
  title: "Max Lorsignol"
  search: false
  navbar:
    left:
#      - href: index.qmd
#        text: Home

      - href: gis.qmd
        text: GIS

      - href: remote_sensing.qmd
        text: Remote Sensing

      - href: personal_projects.qmd
        text: Personal Projects

#       - href: photogrammetry.qmd
#         text: Photogrammetry

#       - href: orthophotography.qmd
#         text: Orthophotography

#       - href: cartography.qmd
#         text: Cartography

    right:
      - href: "Geomatics_Resume.pdf"
        text: CV / Resume

format:
  html:
    css: styles.css
    toc: true

editor: visual
