---
title: "Canopy Campers"
format: html
editor: visual
---

## Page Under Construction

In 2023, two friends and I decided to purchase 3 vehicles (one each) with the idea of creating a small scale business that rents out vans for those seeking to explore the beautiful British Columbia and surrounding areas. Using my experience with building vans, I took on the interior build out task, which involved designing and building modular and functional mini van build outs. Since all the vehicles were of different models, each build was unique and completely costume.

During my time building out and renting these vehicles, I gained valuable experience with:

-   Modelling of van interiors using SketchUp to design fully functional, camper vans that sleep and seat up to 5 guests
-   Custom woodworking: slide out dinette with sink, stove, cooler and storage as well as a full-sized bed
-   Customer interactions including responding to inquiries, showing clients how to use features of the campers and key hand-offs
-   Vehicle maintenance and repairs, regular cleaning, organizing, and stocking of vehicles

Below are a few images of those vehicles and their builds.

!